# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'awesomeDemoProj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for awesomeDemoProj
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  

  target 'awesomeDemoProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'awesomeDemoProj-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for awesomeDemoProj-tvOS

  target 'awesomeDemoProj-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
